// Generated by CoffeeScript 1.6.3
/* modules/twoside
# make modules can be used on both server side and client side.
*/


(function() {
  (function() {
    var normalize, twoside;
    twoside = window.twoside = function(path) {
      var exports, module, modulePath, require;
      path = normalize(path);
      exports = {};
      module = twoside._modules[path] = {
        exports: exports
      };
      modulePath = path.slice(0, path.lastIndexOf("/") + 1);
      require = function(path) {
        path = normalize(modulePath + path);
        module = twoside._modules[path];
        if (!module) {
          throw path + ' is a wrong twoside module path.';
        }
        return module.exports;
      };
      return {
        require: require,
        exports: exports,
        module: module
      };
    };
    twoside._modules = {};
    /* we can alias some external modules.*/

    twoside.alias = function(path, object) {
      return twoside._modules[path] = {
        exports: object
      };
    };
    /* e.g. n browser, if underscore have been imported before, we can alias it like below:*/

    /* twoside.alias('underscore', _)*/

    return normalize = function(path) {
      var head, target, token, _i, _len, _ref;
      if (!path || path === '/') {
        return '/';
      }
      target = [];
      _ref = path.split('/');
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        token = _ref[_i];
        if (token === '..') {
          target.pop();
        } else if (token !== '' && token !== '.') {
          target.push(token);
        }
      }
      /* for IE 6 & 7 - use path.charAt(i), not path[i]*/

      head = path.charAt(0) === '/' || path.charAt(0) === '.' ? '/' : '';
      return head + target.join('/').replace(/[\/]{2,}/g, '/');
    };
  })();

  /* javascript sample
  var m = twoside('/module1'), exports= m.exports, module = m.module, require = m.module;
  (function(require, exports, module){
    // wrapped module definition
  })(require, exports, module);
  */


}).call(this);

/*
//@ sourceMappingURL=twoside.map
*/
